import 'package:dart_openapi_generator/src/date_time_converter.dart';
import 'package:dart_openapi_generator/src/generator/model_generator.dart';
import 'package:dart_openapi_generator/src/layout/model_layout.dart';
import 'package:dart_openapi_generator/src/model/schema_object.dart';
import 'package:dart_openapi_generator/src/model/spec_document.dart';
import 'package:dart_openapi_generator/src/name_registry/name_registry.dart';
import 'package:test/test.dart';

SpecDocument _makeDoc({Map<String, SchemaObject> schemas = const {}}) =>
    SpecDocument(
      specVersion: '3.0.3',
      title: 'Test',
      baseUrl: '',
      schemas: schemas,
      operations: const [],
      securitySchemes: const {},
    );

ModelGenerator _makeGen(SpecDocument doc) {
  final registry = buildNameRegistry(doc);
  return ModelGenerator(
    registry,
    ModelLayout.build(doc, registry),
    DateTimeConverter.iso8601,
  );
}

String _source(SpecDocument doc, String filename) {
  final gen = _makeGen(doc);
  final result = gen.generate(doc);
  return result[filename] ??
      (throw StateError('File not found: $filename. Got: ${result.keys}'));
}

/// Maps every public declaration in [files] to the file declaring it.
///
/// Fails as soon as a name is declared twice: two declarations of the same
/// name mean ambiguous_export on the barrel.
Map<String, String> _declarationOwners(Map<String, String> files) {
  final declPattern = RegExp(
    r'^(?:sealed |final |abstract )*(?:class|enum) (\w+)',
    multiLine: true,
  );
  final owner = <String, String>{};

  for (final entry in files.entries) {
    for (final match in declPattern.allMatches(entry.value)) {
      final name = match.group(1)!;
      if (name.startsWith('_')) continue;
      expect(
        owner,
        isNot(contains(name)),
        reason: '$name is declared in both ${owner[name]} and ${entry.key}',
      );
      owner[name] = entry.key;
    }
  }
  return owner;
}

// --- oneOf fixtures -------------------------------------------------------

const _radius = SchemaProperty(
  specName: 'radius',
  schema: PrimitiveSchema(primitiveType: 'number'),
  isRequired: true,
);
const _side = SchemaProperty(
  specName: 'side',
  schema: PrimitiveSchema(primitiveType: 'number'),
  isRequired: true,
);

const _circle = ObjectSchema(
  name: 'Circle',
  properties: [_radius],
  required: ['radius'],
);
const _square = ObjectSchema(
  name: 'Square',
  properties: [_side],
  required: ['side'],
);
const _shape = OneOfSchema(
  name: 'Shape',
  variants: [_circle, _square],
  discriminatorPropertyName: 'type',
);

const _point = ObjectSchema(name: 'Point', properties: [], required: []);
const _paged = ObjectSchema(name: 'Paged', properties: [], required: []);

const _id = SchemaProperty(
  specName: 'id',
  schema: PrimitiveSchema(primitiveType: 'string'),
  isRequired: true,
);
const _license = SchemaProperty(
  specName: 'license',
  schema: PrimitiveSchema(primitiveType: 'string'),
  isRequired: true,
);

const _customer = ObjectSchema(
  name: 'Customer',
  properties: [_id],
  required: ['id'],
);
const _driver = ObjectSchema(
  name: 'Driver',
  properties: [_id, _license],
  required: ['id', 'license'],
);

/// The spec from the bug report: Customer and Driver are branches of BOTH the
/// request and the response union of one endpoint, and Agency references
/// Customer the ordinary way.
final _reproDoc = _makeDoc(
  schemas: {
    'Agency': const ObjectSchema(
      name: 'Agency',
      properties: [
        _id,
        SchemaProperty(
          specName: 'customer',
          schema: _customer,
          isRequired: true,
        ),
      ],
      required: ['id', 'customer'],
    ),
    'Customer': _customer,
    'Driver': _driver,
    'RegisterRequest': const OneOfSchema(
      name: 'RegisterRequest',
      variants: [_customer, _driver],
    ),
    'RegisterResponse': const OneOfSchema(
      name: 'RegisterResponse',
      variants: [_customer, _driver],
    ),
  },
);

void main() {
  group('ModelGenerator — file header and alphabetical ordering', () {
    test('every emitted file starts with GENERATED CODE header', () {
      final doc = _makeDoc(
        schemas: {
          'User': const ObjectSchema(
            name: 'User',
            properties: [
              SchemaProperty(
                specName: 'id',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
            ],
            required: ['id'],
          ),
        },
      );
      final src = _source(doc, 'models/user.dart');
      expect(src, startsWith('// GENERATED CODE - DO NOT MODIFY BY HAND'));
      expect(src, contains('// Generated by dart_openapi_generator'));
    });

    test('properties emitted in alphabetical order', () {
      final doc = _makeDoc(
        schemas: {
          'Item': const ObjectSchema(
            name: 'Item',
            properties: [
              SchemaProperty(
                specName: 'zebra',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'apple',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'mango',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
            ],
            required: ['zebra', 'apple', 'mango'],
          ),
        },
      );
      final src = _source(doc, 'models/item.dart');
      final appleIdx = src.indexOf('apple');
      final mangoIdx = src.indexOf('mango');
      final zebraIdx = src.indexOf('zebra');
      expect(
        appleIdx,
        lessThan(mangoIdx),
        reason: 'apple must appear before mango',
      );
      expect(
        mangoIdx,
        lessThan(zebraIdx),
        reason: 'mango must appear before zebra',
      );
    });

    test(
      'schema names processed in alphabetical order — generate() keys sorted',
      () {
        final doc = _makeDoc(
          schemas: {
            'Zebra': const ObjectSchema(
              name: 'Zebra',
              properties: [],
              required: [],
            ),
            'Apple': const ObjectSchema(
              name: 'Apple',
              properties: [],
              required: [],
            ),
          },
        );
        final result = _makeGen(doc).generate(doc);
        expect(result.containsKey('models/zebra.dart'), isTrue);
        expect(result.containsKey('models/apple.dart'), isTrue);
      },
    );
  });

  group('ModelGenerator — object class structure', () {
    test(
      'type: object → final class with fromJson, toJson, copyWith, ==, hashCode',
      () {
        final doc = _makeDoc(
          schemas: {
            'User': const ObjectSchema(
              name: 'User',
              properties: [
                SchemaProperty(
                  specName: 'id',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
                SchemaProperty(
                  specName: 'email',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
              ],
              required: ['id', 'email'],
            ),
          },
        );
        final src = _source(doc, 'models/user.dart');
        expect(src, contains('final class User'));
        expect(
          src,
          contains('factory User.fromJson(Map<String, dynamic> json)'),
        );
        expect(src, contains('Map<String, dynamic> toJson()'));
        expect(src, contains('User copyWith('));
        expect(src, contains('bool operator =='));
        expect(src, contains('int get hashCode'));
      },
    );

    test('all-primitive object → const constructor', () {
      final doc = _makeDoc(
        schemas: {
          'Point': const ObjectSchema(
            name: 'Point',
            properties: [
              SchemaProperty(
                specName: 'x',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'y',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
            ],
            required: ['x', 'y'],
          ),
        },
      );
      final src = _source(doc, 'models/point.dart');
      expect(src, contains('const Point('));
    });

    test('object with List field → regular constructor (no const)', () {
      final doc = _makeDoc(
        schemas: {
          'Bag': const ObjectSchema(
            name: 'Bag',
            properties: [
              SchemaProperty(
                specName: 'items',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'string'),
                ),
                isRequired: true,
              ),
            ],
            required: ['items'],
          ),
        },
      );
      final src = _source(doc, 'models/bag.dart');
      // Must NOT have const Bag( — List fields disqualify const
      expect(src, isNot(contains('const Bag(')));
      expect(src, contains('Bag('));
    });
  });

  group('ModelGenerator — deep equality', () {
    test('List field uses _listEquals in == operator', () {
      final doc = _makeDoc(
        schemas: {
          'Tags': const ObjectSchema(
            name: 'Tags',
            properties: [
              SchemaProperty(
                specName: 'labels',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'string'),
                ),
                isRequired: true,
              ),
            ],
            required: ['labels'],
          ),
        },
      );
      final src = _source(doc, 'models/tags.dart');
      expect(src, contains('_listEquals'));
      expect(src, contains('bool _listEquals<T>'));
    });

    test('Map field uses _mapEquals in == operator', () {
      final doc = _makeDoc(
        schemas: {
          'Config': const ObjectSchema(
            name: 'Config',
            properties: [],
            required: [],
            additionalProperties: true,
          ),
        },
      );
      final src = _source(doc, 'models/config.dart');
      expect(src, contains('_mapEquals'));
      expect(src, contains('bool _mapEquals<K, V>'));
    });
  });

  group('ModelGenerator — primitive type mapping', () {
    test('string → String, integer → int, number → double, boolean → bool', () {
      final doc = _makeDoc(
        schemas: {
          'Prim': const ObjectSchema(
            name: 'Prim',
            properties: [
              SchemaProperty(
                specName: 'a',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'b',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'c',
                schema: PrimitiveSchema(primitiveType: 'number'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'd',
                schema: PrimitiveSchema(primitiveType: 'boolean'),
                isRequired: true,
              ),
            ],
            required: ['a', 'b', 'c', 'd'],
          ),
        },
      );
      final src = _source(doc, 'models/prim.dart');
      expect(src, contains('final String a;'));
      expect(src, contains('final int b;'));
      expect(src, contains('final double c;'));
      expect(src, contains('final bool d;'));
    });

    test('array → List<T>', () {
      final doc = _makeDoc(
        schemas: {
          'Arr': const ObjectSchema(
            name: 'Arr',
            properties: [
              SchemaProperty(
                specName: 'items',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'integer'),
                ),
                isRequired: true,
              ),
            ],
            required: ['items'],
          ),
        },
      );
      final src = _source(doc, 'models/arr.dart');
      expect(src, contains('final List<int> items;'));
    });
  });

  group('ModelGenerator — date-time handling', () {
    test('format: date-time → DateTime.parse (iso8601)', () {
      final doc = _makeDoc(
        schemas: {
          'Event': const ObjectSchema(
            name: 'Event',
            properties: [
              SchemaProperty(
                specName: 'created_at',
                schema: PrimitiveSchema(
                  primitiveType: 'string',
                  format: 'date-time',
                ),
                isRequired: true,
              ),
            ],
            required: ['created_at'],
          ),
        },
      );
      final src = _source(doc, 'models/event.dart');
      expect(src, contains('final DateTime createdAt;'));
      expect(src, contains('DateTime.parse('));
      expect(src, contains('toIso8601String()'));
    });
  });

  group('ModelGenerator — anonymous object → Map', () {
    test('anonymous inline ObjectSchema property → Map<String, dynamic>', () {
      final doc = _makeDoc(
        schemas: {
          'Wrapper': const ObjectSchema(
            name: 'Wrapper',
            properties: [
              SchemaProperty(
                specName: 'meta',
                schema: ObjectSchema(
                  // no name — anonymous
                  properties: [],
                  required: [],
                ),
                isRequired: true,
              ),
            ],
            required: ['meta'],
          ),
        },
      );
      final src = _source(doc, 'models/wrapper.dart');
      expect(src, contains('final Map<String, dynamic> meta;'));
    });
  });

  group('ModelGenerator — additionalProperties', () {
    test(
      'additionalProperties: true → Map<String, dynamic> field named additionalProperties',
      () {
        final doc = _makeDoc(
          schemas: {
            'Config': const ObjectSchema(
              name: 'Config',
              properties: [
                SchemaProperty(
                  specName: 'name',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
              ],
              required: ['name'],
              additionalProperties: true,
            ),
          },
        );
        final src = _source(doc, 'models/config.dart');
        expect(
          src,
          contains('final Map<String, dynamic> additionalProperties;'),
        );
        expect(src, contains('final String name;'));
      },
    );
  });

  group('ModelGenerator — enum', () {
    test(
      'enum: wire values preserved verbatim, Dart identifiers camelCased',
      () {
        final doc = _makeDoc(
          schemas: {
            'Status': const EnumSchema(
              name: 'Status',
              enumType: 'string',
              values: ['IN_PROGRESS', 'active', 'DONE'],
            ),
          },
        );
        final src = _source(doc, 'models/status.dart');
        // Dart identifiers must be camelCase
        expect(src, contains('inProgress'));
        expect(src, contains('active'));
        expect(src, contains('done'));
        // Wire values must be preserved verbatim in fromJson/toJson
        expect(src, contains("'IN_PROGRESS'"));
        expect(src, contains("'active'"));
        expect(src, contains("'DONE'"));
      },
    );

    test('enum values emitted in alphabetical order by Dart identifier', () {
      final doc = _makeDoc(
        schemas: {
          'Status': const EnumSchema(
            name: 'Status',
            enumType: 'string',
            values: ['DONE', 'ACTIVE', 'IN_PROGRESS'],
          ),
        },
      );
      final src = _source(doc, 'models/status.dart');
      // After camelCase: active, done, inProgress → alphabetical = active, done, inProgress
      final activeIdx = src.indexOf('active');
      final doneIdx = src.indexOf('done');
      final inProgressIdx = src.indexOf('inProgress');
      expect(activeIdx, lessThan(doneIdx));
      expect(doneIdx, lessThan(inProgressIdx));
    });

    test('digit-leading enum value gets enum prefix', () {
      final doc = _makeDoc(
        schemas: {
          'Speed': const EnumSchema(
            name: 'Speed',
            enumType: 'string',
            values: ['2fast', 'slow'],
          ),
        },
      );
      final src = _source(doc, 'models/speed.dart');
      expect(src, contains('enum2fast'));
      expect(src, contains("'2fast'")); // wire value preserved
    });
  });

  group('ModelGenerator — allOf flat merge', () {
    test(
      'allOf merges properties from all ObjectSchema members into one class',
      () {
        final doc = _makeDoc(
          schemas: {
            'Combined': const AllOfSchema(
              name: 'Combined',
              schemas: [
                ObjectSchema(
                  name: 'Base',
                  properties: [
                    SchemaProperty(
                      specName: 'id',
                      schema: PrimitiveSchema(primitiveType: 'string'),
                      isRequired: true,
                    ),
                  ],
                  required: ['id'],
                ),
                ObjectSchema(
                  name: 'Extended',
                  properties: [
                    SchemaProperty(
                      specName: 'name',
                      schema: PrimitiveSchema(primitiveType: 'string'),
                      isRequired: true,
                    ),
                  ],
                  required: ['name'],
                ),
              ],
            ),
          },
        );
        final src = _source(doc, 'models/combined.dart');
        expect(src, contains('final class Combined'));
        expect(src, contains('final String id;'));
        expect(src, contains('final String name;'));
        // Single class, no inheritance
        expect(src, isNot(contains('extends Base')));
      },
    );
  });

  group('ModelGenerator — oneOf sealed class', () {
    test(r'discriminated oneOf reuses its $ref branches via implements', () {
      final doc = _makeDoc(
        schemas: {'Circle': _circle, 'Shape': _shape, 'Square': _square},
      );
      final src = _source(doc, 'models/shape.dart');

      expect(src, contains('sealed class Shape'));
      expect(src, contains('factory Shape.fromJson'));
      // The components stay components: they are declared once, in the
      // wrapper's library, and wired with implements — never re-declared as
      // private subtypes of the wrapper.
      expect(src, contains('final class Circle implements Shape'));
      expect(src, contains('final class Square implements Shape'));
      expect(src, isNot(contains('extends Shape')));
      expect(src, contains('throw ArgumentError'));
      expect(src, contains('final double radius;'));
      expect(src, contains('final double side;'));
    });

    test(
      'a component used by two unions is declared once, implementing both',
      () {
        // Regression: request and response of the same endpoint both listing the
        // same $ref branches used to emit Customer twice, in two files, with two
        // different supertypes — an ambiguous_export on the barrel.
        final files = _makeGen(_reproDoc).generate(_reproDoc);
        final all = files.values.join('\n');

        expect(
          RegExp(r'final class Customer\b').allMatches(all).length,
          1,
          reason: 'Customer must be declared exactly once across all files',
        );
        expect(
          all,
          contains(
            'final class Customer implements RegisterRequest, RegisterResponse',
          ),
        );
        expect(files.keys, contains('models/register_request.dart'));
        expect(
          files['models/register_request.dart'],
          contains('sealed class RegisterRequest'),
        );
        expect(
          files['models/register_request.dart'],
          contains('sealed class RegisterResponse'),
        );
      },
    );

    test(
      'a schema referencing a clustered component imports the cluster file',
      () {
        // Regression: agency.dart used to import customer.dart, a file the
        // generator never wrote.
        final files = _makeGen(_reproDoc).generate(_reproDoc);
        final agency = files['models/agency.dart']!;

        expect(agency, contains("import 'register_request.dart';"));
        expect(agency, isNot(contains("import 'customer.dart';")));
        expect(agency, contains('final Customer customer;'));
        expect(files.keys, isNot(contains('models/customer.dart')));
      },
    );

    test('oneOf without discriminator decodes by trying the variants', () {
      final files = _makeGen(_reproDoc).generate(_reproDoc);
      final src = files['models/register_request.dart']!;

      expect(src, contains('return Customer.fromJson(json)'));
      expect(src, contains('return Driver.fromJson(json)'));
      expect(src, contains('catch (_) {}'));
      expect(src, contains("no variant matched the payload"));
      expect(src, isNot(contains('UnimplementedError')));
    });

    test('variants are tried most-specific first', () {
      // Customer{id} is a subset of Driver{id, license}: trying Customer first
      // would swallow every Driver payload.
      final src =
          _makeGen(
            _reproDoc,
          ).generate(_reproDoc)['models/register_request.dart']!;
      // The file also declares RegisterResponse.fromJson: scope the body to
      // the closing brace of the factory under test, or the ordering could be
      // asserted on the wrong one.
      final start = src.indexOf('factory RegisterRequest.fromJson');
      final end = src.indexOf('\n  }\n', start);
      expect(start, isNonNegative);
      expect(end, greaterThan(start));
      final body = src.substring(start, end);
      expect(
        body.indexOf('Driver.fromJson'),
        lessThan(body.indexOf('Customer.fromJson')),
      );
    });

    test(
      'a non-object branch becomes a value class and widens the signatures',
      () {
        final doc = _makeDoc(
          schemas: {
            'Point': _point,
            'Paged': _paged,
            'PointsResponse': const OneOfSchema(
              name: 'PointsResponse',
              variants: [
                ObjectSchema(name: 'Paged', properties: [], required: []),
                ArraySchema(
                  items: ObjectSchema(
                    name: 'Point',
                    properties: [],
                    required: [],
                  ),
                ),
              ],
            ),
          },
        );
        final src = _source(doc, 'models/points_response.dart');

        expect(src, contains('sealed class PointsResponse'));
        expect(src, contains('Object? toJson();'));
        expect(src, contains('factory PointsResponse.fromJson(Object? json)'));
        expect(
          src,
          contains(
            'final class PointsResponsePointList extends PointsResponse',
          ),
        );
        expect(src, contains('final List<Point> value;'));
        expect(src, contains('final class Paged implements PointsResponse'));
      },
    );

    test('an anonymous inline branch is still emitted as a subclass', () {
      final doc = _makeDoc(
        schemas: {
          'Thing': const OneOfSchema(
            name: 'Thing',
            variants: [
              ObjectSchema(
                properties: [
                  SchemaProperty(
                    specName: 'a',
                    schema: PrimitiveSchema(primitiveType: 'string'),
                    isRequired: true,
                  ),
                ],
                required: ['a'],
              ),
            ],
          ),
        },
      );
      final src = _source(doc, 'models/thing.dart');

      expect(src, contains('sealed class Thing'));
      expect(src, contains('final class ThingVariant0 extends Thing'));
      expect(src, contains('final String a;'));
    });
  });

  group('ModelGenerator — output invariants', () {
    test('every import in a model file resolves to an emitted file', () {
      // This is the invariant the oneOf bug broke: agency.dart imported a file
      // that was never written. Cheap to check, catches the whole class.
      final files = _makeGen(_reproDoc).generate(_reproDoc);
      final importPattern = RegExp(r"^import '([^:']+)';", multiLine: true);

      for (final entry in files.entries) {
        for (final match in importPattern.allMatches(entry.value)) {
          final target = 'models/${match.group(1)}';
          expect(
            files.keys,
            contains(target),
            reason:
                '${entry.key} imports ${match.group(1)}, which was never emitted',
          );
        }
      }
    });

    test('no class name is declared in two files', () {
      // Two declarations of the same name means ambiguous_export on the barrel.
      _declarationOwners(_makeGen(_reproDoc).generate(_reproDoc));
    });
  });

  group('ModelGenerator — nullable fields', () {
    test('absent-from-required → T? nullable, omitted in toJson if null', () {
      final doc = _makeDoc(
        schemas: {
          'Profile': const ObjectSchema(
            name: 'Profile',
            properties: [
              SchemaProperty(
                specName: 'id',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'bio',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: false,
              ),
            ],
            required: ['id'],
          ),
        },
      );
      final src = _source(doc, 'models/profile.dart');
      expect(src, contains('final String id;'));
      expect(src, contains('final String? bio;'));
      // toJson must guard nullable field
      expect(src, contains('if (bio != null)'));
    });
  });

  group('ModelGenerator — copyWith sentinel', () {
    test(
      'copyWith uses _Undefined sentinel to allow clearing nullable fields',
      () {
        final doc = _makeDoc(
          schemas: {
            'Profile': const ObjectSchema(
              name: 'Profile',
              properties: [
                SchemaProperty(
                  specName: 'id',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
                SchemaProperty(
                  specName: 'bio',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: false,
                ),
              ],
              required: ['id'],
            ),
          },
        );
        final src = _source(doc, 'models/profile.dart');
        expect(src, contains('class _Undefined'));
        expect(src, contains('const _Undefined _undefined'));
        expect(src, contains('Object? bio = _undefined'));
        expect(src, contains('identical(bio, _undefined)'));
      },
    );
  });

  group('ModelGenerator — anonymous array items (items: {})', () {
    test(
      'array property with anonymous items schema → toJson emits list directly, no .toJson()',
      () {
        final doc = _makeDoc(
          schemas: {
            'PageDto': const ObjectSchema(
              name: 'PageDto',
              properties: [
                SchemaProperty(
                  specName: 'data',
                  schema: ArraySchema(
                    items: ObjectSchema(
                      name: null,
                      properties: [],
                      required: [],
                    ),
                  ),
                  isRequired: false,
                ),
              ],
              required: [],
            ),
          },
        );
        final src = _source(doc, 'models/page_dto.dart');
        expect(src, isNot(contains('.toJson()')));
        expect(src, contains("if (data != null) 'data': data"));
      },
    );

    test(
      'array property with anonymous items schema → fromJson uses cast, not fromJson',
      () {
        final doc = _makeDoc(
          schemas: {
            'PageDto': const ObjectSchema(
              name: 'PageDto',
              properties: [
                SchemaProperty(
                  specName: 'data',
                  schema: ArraySchema(
                    items: ObjectSchema(
                      name: null,
                      properties: [],
                      required: [],
                    ),
                  ),
                  isRequired: false,
                ),
              ],
              required: [],
            ),
          },
        );
        final src = _source(doc, 'models/page_dto.dart');
        expect(src, contains('.cast<Map<String, dynamic>>()'));
      },
    );
  });

  group('ModelGenerator — hashCode with >20 fields', () {
    SchemaProperty strProp(String name) => SchemaProperty(
      specName: name,
      schema: const PrimitiveSchema(primitiveType: 'string'),
      isRequired: true,
    );

    test(
      'class with 21 string fields → hashCode uses Object.hashAll, not Object.hash',
      () {
        final props = List.generate(21, (i) => strProp('field$i'));
        final doc = _makeDoc(
          schemas: {
            'BigDto': ObjectSchema(
              name: 'BigDto',
              properties: props,
              required: props.map((p) => p.specName).toList(),
            ),
          },
        );
        final src = _source(doc, 'models/big_dto.dart');
        expect(src, contains('Object.hashAll(['));
        expect(src, isNot(matches(RegExp(r'Object\.hash\([^)]{200,}'))));
      },
    );

    test(
      'class with 20 string fields → hashCode uses Object.hash (not Object.hashAll)',
      () {
        final props = List.generate(20, (i) => strProp('field$i'));
        final doc = _makeDoc(
          schemas: {
            'MedDto': ObjectSchema(
              name: 'MedDto',
              properties: props,
              required: props.map((p) => p.specName).toList(),
            ),
          },
        );
        final src = _source(doc, 'models/med_dto.dart');
        expect(src, contains('Object.hash('));
      },
    );
  });

  group('ModelGenerator — oneOf branch classification', () {
    test(
      'a synthesised value class yields to a real component of the same name',
      () {
        // FooString is a component the user owns; the value holder for the
        // string branch of Foo would be called FooString too. Declaring the
        // name twice is exactly the ambiguous_export the clustering fixes.
        final doc = _makeDoc(
          schemas: {
            'FooString': const ObjectSchema(
              name: 'FooString',
              properties: [_id],
              required: ['id'],
            ),
            'Foo': const OneOfSchema(
              name: 'Foo',
              variants: [PrimitiveSchema(primitiveType: 'string')],
            ),
          },
        );

        final owner = _declarationOwners(_makeGen(doc).generate(doc));
        // The user's component keeps its name; the synthesised one gives way.
        expect(owner['FooString'], 'models/foo_string.dart');
        expect(owner['FooString2'], 'models/foo.dart');
      },
    );

    test(r'an unresolvable $ref branch warns instead of crashing', () {
      // A $ref that resolved outside #/components/schemas: named and
      // class-shaped, but there is no component to reuse.
      final doc = _makeDoc(
        schemas: {
          'Thing': const OneOfSchema(
            name: 'Thing',
            variants: [
              ObjectSchema(name: 'Elsewhere', properties: [], required: []),
              ObjectSchema(name: 'Point', properties: [], required: []),
            ],
          ),
          'Point': _point,
        },
      );
      final warnings = <String>[];
      final registry = buildNameRegistry(doc);
      final files = ModelGenerator(
        registry,
        ModelLayout.build(doc, registry),
        DateTimeConverter.iso8601,
        onWarning: warnings.add,
      ).generate(doc);

      expect(warnings, isNotEmpty);
      expect(warnings.join('\n'), contains('Elsewhere'));
      final src = files['models/thing.dart']!;
      expect(src, contains('sealed class Thing'));
      // The resolvable branch is still wired up; the missing one is dropped.
      expect(src, contains('Point.fromJson'));
      expect(src, isNot(contains('Elsewhere')));
    });

    test(r'a nested oneOf $ref branch joins the same cluster', () {
      final doc = _makeDoc(
        schemas: {
          'Leaf': const ObjectSchema(
            name: 'Leaf',
            properties: [_id],
            required: ['id'],
          ),
          'Inner': const OneOfSchema(
            name: 'Inner',
            variants: [
              ObjectSchema(name: 'Leaf', properties: [_id], required: ['id']),
            ],
          ),
          'Outer': const OneOfSchema(
            name: 'Outer',
            variants: [
              OneOfSchema(
                name: 'Inner',
                variants: [
                  ObjectSchema(
                    name: 'Leaf',
                    properties: [_id],
                    required: ['id'],
                  ),
                ],
              ),
            ],
          ),
        },
      );
      final files = _makeGen(doc).generate(doc);

      expect(files.keys, ['models/inner.dart']);
      final src = files['models/inner.dart']!;
      expect(src, contains('sealed class Inner implements Outer'));
      expect(src, contains('sealed class Outer'));
      expect(src, contains('final class Leaf implements Inner'));
    });
  });
}
