import 'dart:convert';
import 'dart:io';

import 'package:dart_openapi_generator/src/resolved_annotation.dart';
import 'package:dart_openapi_generator/src/writer/file_writer.dart';
import 'package:dart_openapi_generator_annotations/dart_openapi_generator_annotations.dart';
import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';
import 'package:test/test.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

ResolvedAnnotation _makeAnnotation({
  required String outputDir,
  required String cachePath,
  bool cleanOutput = false,
  bool debugLogging = false,
}) => ResolvedAnnotation(
  inputSpec: const LocalSpec('openapi.yaml'),
  outputDir: outputDir,
  clientName: 'ApiClient',
  skipIfSpecIsUnchanged: true,
  cachePath: cachePath,
  cleanOutput: cleanOutput,
  dateTimeConverter: DateTimeConverter.iso8601,
  debugLogging: debugLogging,
);

/// Simple valid Dart source that the formatter accepts.
const _validSource = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart=3.0
// Generated by dart_openapi_generator

class User {}
''';

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  // -------------------------------------------------------------------------
  // File write to disk
  // -------------------------------------------------------------------------
  group('file write to disk', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('write() creates file at outputDir/key path', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      final created = File('${tmpDir.path}/models/user.dart');
      expect(
        created.existsSync(),
        isTrue,
        reason: 'models/user.dart must exist on disk',
      );
    });

    test('written file content matches formatted source', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      final content =
          File('${tmpDir.path}/models/user.dart').readAsStringSync();
      expect(content, isNotEmpty);
      // Content must be valid Dart (formatter round-trip is idempotent)
      final formatter = DartFormatter(languageVersion: Version(3, 0, 0));
      final reformatted = formatter.format(content, uri: 'models/user.dart');
      expect(
        content,
        equals(reformatted),
        reason: 'written file must be idempotent under dart_style',
      );
    });
  });

  // -------------------------------------------------------------------------
  // Subdirectory layout (models/, services/)
  // -------------------------------------------------------------------------
  group('subdirectory layout', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('key "models/user.dart" creates parent dir and file', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      expect(
        Directory('${tmpDir.path}/models').existsSync(),
        isTrue,
        reason: 'models/ subdirectory must be created',
      );
      expect(
        File('${tmpDir.path}/models/user.dart').existsSync(),
        isTrue,
        reason: 'models/user.dart must exist',
      );
    });

    test('key "services/pet_api.dart" creates parent dir and file', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'services/pet_api.dart': _validSource,
      }, annotation);

      expect(
        Directory('${tmpDir.path}/services').existsSync(),
        isTrue,
        reason: 'services/ subdirectory must be created',
      );
      expect(
        File('${tmpDir.path}/services/pet_api.dart').existsSync(),
        isTrue,
        reason: 'services/pet_api.dart must exist',
      );
    });
  });

  // -------------------------------------------------------------------------
  // Barrel generation
  // -------------------------------------------------------------------------
  group('barrel generation', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('barrel file generated.dart is written to disk', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      expect(
        File('${tmpDir.path}/generated.dart').existsSync(),
        isTrue,
        reason: 'generated.dart barrel must be created',
      );
    });

    test('barrel exports are in alphabetical order', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'services/b_api.dart': _validSource,
        'models/a.dart': _validSource,
      }, annotation);

      final barrel = File('${tmpDir.path}/generated.dart').readAsStringSync();
      final aIdx = barrel.indexOf("export 'models/a.dart'");
      final bIdx = barrel.indexOf("export 'services/b_api.dart'");
      expect(
        aIdx,
        lessThan(bIdx),
        reason: 'models/a.dart must appear before services/b_api.dart',
      );
    });

    test('barrel does NOT export generated.dart itself', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      final barrel = File('${tmpDir.path}/generated.dart').readAsStringSync();
      expect(
        barrel,
        isNot(contains("export 'generated.dart'")),
        reason: 'barrel must not export itself',
      );
    });

    test('barrel uses correct export syntax', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      final barrel = File('${tmpDir.path}/generated.dart').readAsStringSync();
      expect(barrel, contains("export 'models/user.dart'"));
    });
  });

  // -------------------------------------------------------------------------
  // Path safety guard
  // -------------------------------------------------------------------------
  group('path safety guard', () {
    late Directory cacheDir;

    setUp(() async {
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('outputDir == "/" throws StateError', () async {
      final annotation = _makeAnnotation(
        outputDir: '/',
        cachePath: cacheDir.path,
      );
      await expectLater(
        () async => const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation),
        throwsA(isA<StateError>()),
      );
    });

    test('outputDir == "." throws StateError', () async {
      final annotation = _makeAnnotation(
        outputDir: '.',
        cachePath: cacheDir.path,
      );
      await expectLater(
        () async => const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation),
        throwsA(isA<StateError>()),
      );
    });

    test('outputDir == "lib" throws StateError', () async {
      final annotation = _makeAnnotation(
        outputDir: 'lib',
        cachePath: cacheDir.path,
      );
      await expectLater(
        () async => const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation),
        throwsA(isA<StateError>()),
      );
    });

    test('outputDir containing ".." throws StateError', () async {
      final annotation = _makeAnnotation(
        outputDir: 'lib/../secrets',
        cachePath: cacheDir.path,
      );
      await expectLater(
        () async => const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation),
        throwsA(isA<StateError>()),
      );
    });

    test('outputDir is a symlink throws StateError', () async {
      final realDir = await Directory.systemTemp.createTemp(
        'file_writer_real_',
      );
      addTearDown(() async {
        if (realDir.existsSync()) await realDir.delete(recursive: true);
      });
      final symlinkPath =
          '${Directory.systemTemp.path}/file_writer_symlink_${realDir.path.hashCode}';
      final link = Link(symlinkPath);
      link.createSync(realDir.path);
      addTearDown(() {
        if (link.existsSync()) link.deleteSync();
      });

      final annotation = _makeAnnotation(
        outputDir: symlinkPath,
        cachePath: cacheDir.path,
      );
      await expectLater(
        () async => const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation),
        throwsA(isA<StateError>()),
      );
    });

    test('outputDir "lib/generated" (safe path) does NOT throw', () async {
      final safeDir = await Directory.systemTemp.createTemp(
        'file_writer_safe_',
      );
      addTearDown(() async {
        if (safeDir.existsSync()) await safeDir.delete(recursive: true);
      });
      // Use an absolute safe path (not the project lib — a temp dir with /generated subdir)
      final safeOutputDir = '${safeDir.path}/generated';
      final annotation = _makeAnnotation(
        outputDir: safeOutputDir,
        cachePath: cacheDir.path,
      );
      // Must NOT throw — directly await
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);
    });
  });

  // -------------------------------------------------------------------------
  // Manifest write
  // -------------------------------------------------------------------------
  group('manifest write', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('manifest.json is created at cachePath after write()', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      expect(
        File('${cacheDir.path}/manifest.json').existsSync(),
        isTrue,
        reason: 'manifest.json must be created in cachePath',
      );
    });

    test('manifest JSON has {"files": [...]} structure', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);

      final content = File('${cacheDir.path}/manifest.json').readAsStringSync();
      final data = jsonDecode(content) as Map<String, dynamic>;
      expect(data, containsPair('files', isA<List>()));
    });

    test(
      'manifest contains all written relative paths in sorted order',
      () async {
        final annotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
        );
        await const FileWriter().write({
          'services/z_api.dart': _validSource,
          'models/a.dart': _validSource,
        }, annotation);

        final content =
            File('${cacheDir.path}/manifest.json').readAsStringSync();
        final data = jsonDecode(content) as Map<String, dynamic>;
        final files = (data['files'] as List).cast<String>();
        // Must contain models/a.dart, services/z_api.dart, generated.dart
        expect(
          files,
          containsAll([
            'models/a.dart',
            'services/z_api.dart',
            'generated.dart',
          ]),
        );
        // Must be sorted
        final sorted = files.toList()..sort();
        expect(
          files,
          equals(sorted),
          reason: 'manifest files must be alphabetically sorted',
        );
      },
    );
  });

  // -------------------------------------------------------------------------
  // dart_style post-pass
  // -------------------------------------------------------------------------
  group('dart_style post-pass', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test(
      'written file is idempotent under dart_style (formatter already applied)',
      () async {
        const unformatted = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart=3.0
// Generated by dart_openapi_generator

class User{final String name;User({required this.name});}
''';
        final annotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
        );
        await const FileWriter().write({
          'models/user.dart': unformatted,
        }, annotation);

        final written =
            File('${tmpDir.path}/models/user.dart').readAsStringSync();
        final formatter = DartFormatter(languageVersion: Version(3, 0, 0));
        final reformatted = formatter.format(written, uri: 'models/user.dart');
        expect(
          written,
          equals(reformatted),
          reason: 'written file should be formatter-idempotent',
        );
      },
    );
  });

  // -------------------------------------------------------------------------
  // Debug logging
  // -------------------------------------------------------------------------
  group('debug logging', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('onLog called with "wrote" message for each file written', () async {
      final logs = <String>[];
      final writer = FileWriter(onLog: logs.add);
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      await writer.write({
        'models/user.dart': _validSource,
        'services/user_api.dart': _validSource,
      }, annotation);

      // Expect log entries containing 'wrote' for each file (+ generated.dart barrel)
      final wroteMessages = logs.where((m) => m.contains('wrote')).toList();
      expect(
        wroteMessages.length,
        greaterThanOrEqualTo(3),
        reason:
            'Should log "wrote" for models/user.dart, services/user_api.dart, and generated.dart',
      );
    });

    test('null onLog causes no errors', () async {
      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
      );
      // Directly await — if it throws, the test fails; if not, it passes
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, annotation);
    });
  });

  // -------------------------------------------------------------------------
  // cleanOutput manifest-driven deletion
  // -------------------------------------------------------------------------
  group('cleanOutput manifest-driven', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test(
      'cleanOutput: manifest-listed files are deleted before re-generation',
      () async {
        // First write: creates files and manifest
        final firstAnnotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
          cleanOutput: false,
        );
        await const FileWriter().write({
          'models/old.dart': _validSource,
        }, firstAnnotation);

        // Verify first write created the file
        expect(File('${tmpDir.path}/models/old.dart').existsSync(), isTrue);

        // Second write with cleanOutput: true — manifest from first run lists old.dart + generated.dart
        final cleanAnnotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
          cleanOutput: true,
        );
        await const FileWriter().write({
          'models/new.dart': _validSource,
        }, cleanAnnotation);

        // old.dart should be deleted (it was in the manifest)
        expect(
          File('${tmpDir.path}/models/old.dart').existsSync(),
          isFalse,
          reason: 'Manifest-listed old.dart must be deleted on cleanOutput',
        );
      },
    );

    test('cleanOutput: non-manifest files survive deletion', () async {
      // Create a non-generated file in the output dir
      final nonGenFile = File('${tmpDir.path}/user.txt');
      await nonGenFile.writeAsString('not generated');

      // First write creates manifest
      final firstAnnotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
        cleanOutput: false,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, firstAnnotation);

      // Second write with cleanOutput deletes only manifest-listed files
      final cleanAnnotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
        cleanOutput: true,
      );
      await const FileWriter().write({
        'models/user.dart': _validSource,
      }, cleanAnnotation);

      // user.txt is NOT in the manifest → must survive
      expect(
        nonGenFile.existsSync(),
        isTrue,
        reason: 'Non-manifest user.txt must survive cleanOutput',
      );
    });
  });

  // -------------------------------------------------------------------------
  // cleanOutput first-run fallback (no manifest)
  // -------------------------------------------------------------------------
  group('cleanOutput first-run fallback', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test('cleanOutput first-run: models/*.dart files are deleted', () async {
      // Create a stale model file without a manifest
      final modelsDir = Directory('${tmpDir.path}/models');
      await modelsDir.create(recursive: true);
      final staleModel = File('${modelsDir.path}/stale.dart');
      await staleModel.writeAsString('class Stale {}');

      final annotation = _makeAnnotation(
        outputDir: tmpDir.path,
        cachePath: cacheDir.path,
        cleanOutput: true,
      );
      await const FileWriter().write({
        'models/new.dart': _validSource,
      }, annotation);

      expect(
        staleModel.existsSync(),
        isFalse,
        reason:
            'Stale .dart files in models/ must be deleted in first-run clean',
      );
    });

    test(
      'cleanOutput first-run: non-dart files in output dir survive',
      () async {
        // Create a non-dart file that should NOT be deleted
        final txtFile = File('${tmpDir.path}/readme.txt');
        await txtFile.writeAsString('keep me');

        final annotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
          cleanOutput: true,
        );
        await const FileWriter().write({
          'models/user.dart': _validSource,
        }, annotation);

        expect(
          txtFile.existsSync(),
          isTrue,
          reason: 'Non-dart files must survive first-run cleanOutput',
        );
      },
    );
  });

  // -------------------------------------------------------------------------
  // Manifest poisoning protection
  // -------------------------------------------------------------------------
  group('manifest poisoning protection', () {
    late Directory tmpDir;
    late Directory cacheDir;

    setUp(() async {
      tmpDir = await Directory.systemTemp.createTemp('file_writer_test_');
      cacheDir = await Directory.systemTemp.createTemp('file_writer_cache_');
      addTearDown(() async {
        if (tmpDir.existsSync()) await tmpDir.delete(recursive: true);
        if (cacheDir.existsSync()) await cacheDir.delete(recursive: true);
      });
    });

    test(
      'manifest entry containing ".." is skipped and log message captured',
      () async {
        // Create a real file that we want to survive
        final safeFile = File('${tmpDir.path}/models/safe.dart');
        await safeFile.parent.create(recursive: true);
        await safeFile.writeAsString('class Safe {}');

        // Create a poisoned manifest with a '..' path traversal entry
        final manifestFile = File('${cacheDir.path}/manifest.json');
        await manifestFile.parent.create(recursive: true);
        await manifestFile.writeAsString(
          jsonEncode({
            'files': ['models/safe.dart', '../secret_file.dart'],
          }),
        );

        // The '..' entry should be skipped (not deleted), and log should capture the skip
        final logs = <String>[];
        final writer = FileWriter(onLog: logs.add);
        final annotation = _makeAnnotation(
          outputDir: tmpDir.path,
          cachePath: cacheDir.path,
          cleanOutput: true,
        );
        await writer.write({'models/safe.dart': _validSource}, annotation);

        // The '..' entry must be skipped — log must mention it
        final skipLogs =
            logs
                .where((m) => m.contains('skipping') || m.contains('unsafe'))
                .toList();
        expect(
          skipLogs,
          isNotEmpty,
          reason:
              'A skip log message must be emitted for the ".." manifest entry',
        );
      },
    );
  });
}
