import 'package:dart_openapi_generator/src/builder/open_api_builder.dart';
import 'package:dart_openapi_generator/src/writer/file_writer.dart';
import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';
import 'package:test/test.dart';

/// Simple valid Dart source that the formatter accepts.
const _validSource = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart=3.0
// Generated by dart_openapi_generator

class User {}
''';

Map<String, String> _prepare(
  Map<String, String> files, {
  String barrelFileName = 'generated.dart',
}) => const FileWriter().prepare(files, barrelFileName: barrelFileName);

void main() {
  group('prepare()', () {
    test('returns a formatted entry for each input key', () {
      final result = _prepare({'models/user.dart': _validSource});

      expect(result['models/user.dart'], isNotEmpty);
    });

    test('written content is idempotent under dart_style', () {
      const unformatted = '''
// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart=3.0
// Generated by dart_openapi_generator

class User{final String name;User({required this.name});}
''';
      final result = _prepare({'models/user.dart': unformatted});
      final written = result['models/user.dart']!;

      final formatter = DartFormatter(languageVersion: Version(3, 0, 0));
      final reformatted = formatter.format(written, uri: 'models/user.dart');
      expect(
        written,
        equals(reformatted),
        reason: 'prepared source should be formatter-idempotent',
      );
    });

    test('formatter error falls back to unformatted source', () {
      const broken = 'class User { this is not valid dart';
      final result = _prepare({'models/user.dart': broken});
      expect(result['models/user.dart'], equals(broken));
    });
  });

  group('barrel generation', () {
    test('adds generated.dart exporting all inputs', () {
      final result = _prepare({'models/user.dart': _validSource});
      expect(result, contains('generated.dart'));
      expect(result['generated.dart'], contains("export 'models/user.dart'"));
    });

    test('barrel exports are in alphabetical order', () {
      final result = _prepare({
        'services/b_api.dart': _validSource,
        'models/a.dart': _validSource,
      });
      final barrel = result['generated.dart']!;
      final aIdx = barrel.indexOf("export 'models/a.dart'");
      final bIdx = barrel.indexOf("export 'services/b_api.dart'");
      expect(
        aIdx,
        lessThan(bIdx),
        reason: 'models/a.dart must appear before services/b_api.dart',
      );
    });

    test('barrel does NOT export generated.dart itself', () {
      final result = _prepare({'models/user.dart': _validSource});
      expect(
        result['generated.dart'],
        isNot(contains("export 'generated.dart'")),
        reason: 'barrel must not export itself',
      );
    });

    test('barrel file name is configurable via barrelFileName', () {
      final result = _prepare({
        'models/user.dart': _validSource,
      }, barrelFileName: 'petstore_client.dart');
      expect(result, isNot(contains('generated.dart')));
      expect(result, contains('petstore_client.dart'));
      expect(
        result['petstore_client.dart'],
        contains("export 'models/user.dart'"),
      );
    });
  });

  group('OpenApiBuilder.barrelBaseName', () {
    test('single-segment outputDir "lib/generated" → "generated"', () {
      expect(
        OpenApiBuilder.barrelBaseName('lib/generated'),
        equals('generated'),
      );
    });

    test('nested outputDir uses the last path segment', () {
      expect(
        OpenApiBuilder.barrelBaseName('lib/services/network/petstore_client'),
        equals('petstore_client'),
      );
    });

    test('trailing slash is ignored', () {
      expect(
        OpenApiBuilder.barrelBaseName('lib/generated/'),
        equals('generated'),
      );
    });

    test('spaces and hyphens in the last segment are normalized', () {
      expect(
        OpenApiBuilder.barrelBaseName('lib/Pet Store-Client'),
        equals('pet_store_client'),
      );
    });
  });

  group('unsafe file keys', () {
    test('key containing ".." throws StateError', () {
      expect(
        () => _prepare({'../secrets/x.dart': _validSource}),
        throwsA(isA<StateError>()),
      );
    });

    test('absolute path key throws StateError', () {
      expect(
        () => _prepare({'/etc/x.dart': _validSource}),
        throwsA(isA<StateError>()),
      );
    });
  });

  group('logging', () {
    test('onLog called once per prepared file (including barrel)', () {
      final logs = <String>[];
      final writer = FileWriter(onLog: logs.add);
      writer.prepare({
        'models/user.dart': _validSource,
        'services/user_api.dart': _validSource,
      }, barrelFileName: 'generated.dart');
      expect(logs, hasLength(3)); // 2 inputs + barrel
    });

    test('onWarning called when there are no files to export', () {
      final warnings = <String>[];
      final writer = FileWriter(onWarning: warnings.add);
      writer.prepare({}, barrelFileName: 'generated.dart');
      expect(warnings, isNotEmpty);
    });

    test('null onLog/onWarning causes no errors', () {
      _prepare({'models/user.dart': _validSource});
    });
  });
}
