import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

final _emitter = DartEmitter(
  allocator: Allocator.none,
  orderDirectives: false,
  useNullSafetySyntax: true,
);

final _formatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);

const _fileHeader =
    '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
    '// @dart=3.0\n'
    '// Generated by dart_openapi_generator\n\n';

String emitLibrary(Library library) {
  final raw = _fileHeader + library.accept(_emitter).toString();
  return _formatter.format(raw);
}
