import 'package:dart_openapi_generator/src/generator/model_generator.dart';
import 'package:dart_openapi_generator/src/model/schema_object.dart';
import 'package:dart_openapi_generator/src/model/spec_document.dart';
import 'package:dart_openapi_generator/src/name_registry/name_registry.dart';
import 'package:dart_openapi_generator_annotations/dart_openapi_generator_annotations.dart';
import 'package:test/test.dart';

SpecDocument _makeDoc({Map<String, SchemaObject> schemas = const {}}) =>
    SpecDocument(
      specVersion: '3.0.3',
      title: 'Test',
      baseUrl: '',
      schemas: schemas,
      operations: const [],
      securitySchemes: const {},
    );

ModelGenerator _makeGen(SpecDocument doc) =>
    ModelGenerator(buildNameRegistry(doc), DateTimeConverter.iso8601);

String _source(SpecDocument doc, String filename) {
  final gen = _makeGen(doc);
  final result = gen.generate(doc);
  return result[filename] ??
      (throw StateError('File not found: $filename. Got: ${result.keys}'));
}

void main() {
  group('ModelGenerator — file header and alphabetical ordering', () {
    test('every emitted file starts with GENERATED CODE header', () {
      final doc = _makeDoc(
        schemas: {
          'User': const ObjectSchema(
            name: 'User',
            properties: [
              SchemaProperty(
                specName: 'id',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
            ],
            required: ['id'],
          ),
        },
      );
      final src = _source(doc, 'models/user.dart');
      expect(src, startsWith('// GENERATED CODE - DO NOT MODIFY BY HAND'));
      expect(src, contains('// Generated by dart_openapi_generator'));
    });

    test('properties emitted in alphabetical order', () {
      final doc = _makeDoc(
        schemas: {
          'Item': const ObjectSchema(
            name: 'Item',
            properties: [
              SchemaProperty(
                specName: 'zebra',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'apple',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'mango',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
            ],
            required: ['zebra', 'apple', 'mango'],
          ),
        },
      );
      final src = _source(doc, 'models/item.dart');
      final appleIdx = src.indexOf('apple');
      final mangoIdx = src.indexOf('mango');
      final zebraIdx = src.indexOf('zebra');
      expect(
        appleIdx,
        lessThan(mangoIdx),
        reason: 'apple must appear before mango',
      );
      expect(
        mangoIdx,
        lessThan(zebraIdx),
        reason: 'mango must appear before zebra',
      );
    });

    test(
      'schema names processed in alphabetical order — generate() keys sorted',
      () {
        final doc = _makeDoc(
          schemas: {
            'Zebra': const ObjectSchema(
              name: 'Zebra',
              properties: [],
              required: [],
            ),
            'Apple': const ObjectSchema(
              name: 'Apple',
              properties: [],
              required: [],
            ),
          },
        );
        final result = _makeGen(doc).generate(doc);
        expect(result.containsKey('models/zebra.dart'), isTrue);
        expect(result.containsKey('models/apple.dart'), isTrue);
      },
    );
  });

  group('ModelGenerator — object class structure', () {
    test(
      'type: object → final class with fromJson, toJson, copyWith, ==, hashCode',
      () {
        final doc = _makeDoc(
          schemas: {
            'User': const ObjectSchema(
              name: 'User',
              properties: [
                SchemaProperty(
                  specName: 'id',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
                SchemaProperty(
                  specName: 'email',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
              ],
              required: ['id', 'email'],
            ),
          },
        );
        final src = _source(doc, 'models/user.dart');
        expect(src, contains('final class User'));
        expect(
          src,
          contains('factory User.fromJson(Map<String, dynamic> json)'),
        );
        expect(src, contains('Map<String, dynamic> toJson()'));
        expect(src, contains('User copyWith('));
        expect(src, contains('bool operator =='));
        expect(src, contains('int get hashCode'));
      },
    );

    test('all-primitive object → const constructor', () {
      final doc = _makeDoc(
        schemas: {
          'Point': const ObjectSchema(
            name: 'Point',
            properties: [
              SchemaProperty(
                specName: 'x',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'y',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
            ],
            required: ['x', 'y'],
          ),
        },
      );
      final src = _source(doc, 'models/point.dart');
      expect(src, contains('const Point('));
    });

    test('object with List field → regular constructor (no const)', () {
      final doc = _makeDoc(
        schemas: {
          'Bag': const ObjectSchema(
            name: 'Bag',
            properties: [
              SchemaProperty(
                specName: 'items',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'string'),
                ),
                isRequired: true,
              ),
            ],
            required: ['items'],
          ),
        },
      );
      final src = _source(doc, 'models/bag.dart');
      // Must NOT have const Bag( — List fields disqualify const
      expect(src, isNot(contains('const Bag(')));
      expect(src, contains('Bag('));
    });
  });

  group('ModelGenerator — deep equality', () {
    test('List field uses _listEquals in == operator', () {
      final doc = _makeDoc(
        schemas: {
          'Tags': const ObjectSchema(
            name: 'Tags',
            properties: [
              SchemaProperty(
                specName: 'labels',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'string'),
                ),
                isRequired: true,
              ),
            ],
            required: ['labels'],
          ),
        },
      );
      final src = _source(doc, 'models/tags.dart');
      expect(src, contains('_listEquals'));
      expect(src, contains('bool _listEquals<T>'));
    });

    test('Map field uses _mapEquals in == operator', () {
      final doc = _makeDoc(
        schemas: {
          'Config': const ObjectSchema(
            name: 'Config',
            properties: [],
            required: [],
            additionalProperties: true,
          ),
        },
      );
      final src = _source(doc, 'models/config.dart');
      expect(src, contains('_mapEquals'));
      expect(src, contains('bool _mapEquals<K, V>'));
    });
  });

  group('ModelGenerator — primitive type mapping', () {
    test('string → String, integer → int, number → double, boolean → bool', () {
      final doc = _makeDoc(
        schemas: {
          'Prim': const ObjectSchema(
            name: 'Prim',
            properties: [
              SchemaProperty(
                specName: 'a',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'b',
                schema: PrimitiveSchema(primitiveType: 'integer'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'c',
                schema: PrimitiveSchema(primitiveType: 'number'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'd',
                schema: PrimitiveSchema(primitiveType: 'boolean'),
                isRequired: true,
              ),
            ],
            required: ['a', 'b', 'c', 'd'],
          ),
        },
      );
      final src = _source(doc, 'models/prim.dart');
      expect(src, contains('final String a;'));
      expect(src, contains('final int b;'));
      expect(src, contains('final double c;'));
      expect(src, contains('final bool d;'));
    });

    test('array → List<T>', () {
      final doc = _makeDoc(
        schemas: {
          'Arr': const ObjectSchema(
            name: 'Arr',
            properties: [
              SchemaProperty(
                specName: 'items',
                schema: ArraySchema(
                  items: PrimitiveSchema(primitiveType: 'integer'),
                ),
                isRequired: true,
              ),
            ],
            required: ['items'],
          ),
        },
      );
      final src = _source(doc, 'models/arr.dart');
      expect(src, contains('final List<int> items;'));
    });
  });

  group('ModelGenerator — date-time handling', () {
    test('format: date-time → DateTime.parse (iso8601)', () {
      final doc = _makeDoc(
        schemas: {
          'Event': const ObjectSchema(
            name: 'Event',
            properties: [
              SchemaProperty(
                specName: 'created_at',
                schema: PrimitiveSchema(
                  primitiveType: 'string',
                  format: 'date-time',
                ),
                isRequired: true,
              ),
            ],
            required: ['created_at'],
          ),
        },
      );
      final src = _source(doc, 'models/event.dart');
      expect(src, contains('final DateTime createdAt;'));
      expect(src, contains('DateTime.parse('));
      expect(src, contains('toIso8601String()'));
    });
  });

  group('ModelGenerator — anonymous object → Map', () {
    test('anonymous inline ObjectSchema property → Map<String, dynamic>', () {
      final doc = _makeDoc(
        schemas: {
          'Wrapper': const ObjectSchema(
            name: 'Wrapper',
            properties: [
              SchemaProperty(
                specName: 'meta',
                schema: ObjectSchema(
                  // no name — anonymous
                  properties: [],
                  required: [],
                ),
                isRequired: true,
              ),
            ],
            required: ['meta'],
          ),
        },
      );
      final src = _source(doc, 'models/wrapper.dart');
      expect(src, contains('final Map<String, dynamic> meta;'));
    });
  });

  group('ModelGenerator — additionalProperties', () {
    test(
      'additionalProperties: true → Map<String, dynamic> field named additionalProperties',
      () {
        final doc = _makeDoc(
          schemas: {
            'Config': const ObjectSchema(
              name: 'Config',
              properties: [
                SchemaProperty(
                  specName: 'name',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
              ],
              required: ['name'],
              additionalProperties: true,
            ),
          },
        );
        final src = _source(doc, 'models/config.dart');
        expect(
          src,
          contains('final Map<String, dynamic> additionalProperties;'),
        );
        expect(src, contains('final String name;'));
      },
    );
  });

  group('ModelGenerator — enum', () {
    test(
      'enum: wire values preserved verbatim, Dart identifiers camelCased',
      () {
        final doc = _makeDoc(
          schemas: {
            'Status': const EnumSchema(
              name: 'Status',
              enumType: 'string',
              values: ['IN_PROGRESS', 'active', 'DONE'],
            ),
          },
        );
        final src = _source(doc, 'models/status.dart');
        // Dart identifiers must be camelCase
        expect(src, contains('inProgress'));
        expect(src, contains('active'));
        expect(src, contains('done'));
        // Wire values must be preserved verbatim in fromJson/toJson
        expect(src, contains("'IN_PROGRESS'"));
        expect(src, contains("'active'"));
        expect(src, contains("'DONE'"));
      },
    );

    test('enum values emitted in alphabetical order by Dart identifier', () {
      final doc = _makeDoc(
        schemas: {
          'Status': const EnumSchema(
            name: 'Status',
            enumType: 'string',
            values: ['DONE', 'ACTIVE', 'IN_PROGRESS'],
          ),
        },
      );
      final src = _source(doc, 'models/status.dart');
      // After camelCase: active, done, inProgress → alphabetical = active, done, inProgress
      final activeIdx = src.indexOf('active');
      final doneIdx = src.indexOf('done');
      final inProgressIdx = src.indexOf('inProgress');
      expect(activeIdx, lessThan(doneIdx));
      expect(doneIdx, lessThan(inProgressIdx));
    });

    test('digit-leading enum value gets enum prefix', () {
      final doc = _makeDoc(
        schemas: {
          'Speed': const EnumSchema(
            name: 'Speed',
            enumType: 'string',
            values: ['2fast', 'slow'],
          ),
        },
      );
      final src = _source(doc, 'models/speed.dart');
      expect(src, contains('enum2fast'));
      expect(src, contains("'2fast'")); // wire value preserved
    });
  });

  group('ModelGenerator — allOf flat merge', () {
    test(
      'allOf merges properties from all ObjectSchema members into one class',
      () {
        final doc = _makeDoc(
          schemas: {
            'Combined': const AllOfSchema(
              name: 'Combined',
              schemas: [
                ObjectSchema(
                  name: 'Base',
                  properties: [
                    SchemaProperty(
                      specName: 'id',
                      schema: PrimitiveSchema(primitiveType: 'string'),
                      isRequired: true,
                    ),
                  ],
                  required: ['id'],
                ),
                ObjectSchema(
                  name: 'Extended',
                  properties: [
                    SchemaProperty(
                      specName: 'name',
                      schema: PrimitiveSchema(primitiveType: 'string'),
                      isRequired: true,
                    ),
                  ],
                  required: ['name'],
                ),
              ],
            ),
          },
        );
        final src = _source(doc, 'models/combined.dart');
        expect(src, contains('final class Combined'));
        expect(src, contains('final String id;'));
        expect(src, contains('final String name;'));
        // Single class, no inheritance
        expect(src, isNot(contains('extends Base')));
      },
    );
  });

  group('ModelGenerator — oneOf sealed class', () {
    test('oneOf → sealed parent class + subclass per variant in same file', () {
      // All referenced names must be in the registry
      final doc = _makeDoc(
        schemas: {
          'Circle': const ObjectSchema(
            name: 'Circle',
            properties: [
              SchemaProperty(
                specName: 'radius',
                schema: PrimitiveSchema(primitiveType: 'number'),
                isRequired: true,
              ),
            ],
            required: ['radius'],
          ),
          'Shape': const OneOfSchema(
            name: 'Shape',
            variants: [
              ObjectSchema(
                name: 'Circle',
                properties: [
                  SchemaProperty(
                    specName: 'radius',
                    schema: PrimitiveSchema(primitiveType: 'number'),
                    isRequired: true,
                  ),
                ],
                required: ['radius'],
              ),
              ObjectSchema(
                name: 'Square',
                properties: [
                  SchemaProperty(
                    specName: 'side',
                    schema: PrimitiveSchema(primitiveType: 'number'),
                    isRequired: true,
                  ),
                ],
                required: ['side'],
              ),
            ],
            discriminatorPropertyName: 'type',
          ),
          'Square': const ObjectSchema(
            name: 'Square',
            properties: [
              SchemaProperty(
                specName: 'side',
                schema: PrimitiveSchema(primitiveType: 'number'),
                isRequired: true,
              ),
            ],
            required: ['side'],
          ),
        },
      );
      final src = _source(doc, 'models/shape.dart');
      expect(src, contains('sealed class Shape'));
      expect(src, contains('factory Shape.fromJson'));
      expect(src, contains('final class Circle extends Shape'));
      expect(src, contains('final class Square extends Shape'));
      expect(src, contains('throw ArgumentError'));
      // All in same file — both subclasses present
      expect(src, contains('final double radius;'));
      expect(src, contains('final double side;'));
    });
  });

  group('ModelGenerator — nullable fields', () {
    test('absent-from-required → T? nullable, omitted in toJson if null', () {
      final doc = _makeDoc(
        schemas: {
          'Profile': const ObjectSchema(
            name: 'Profile',
            properties: [
              SchemaProperty(
                specName: 'id',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: true,
              ),
              SchemaProperty(
                specName: 'bio',
                schema: PrimitiveSchema(primitiveType: 'string'),
                isRequired: false,
              ),
            ],
            required: ['id'],
          ),
        },
      );
      final src = _source(doc, 'models/profile.dart');
      expect(src, contains('final String id;'));
      expect(src, contains('final String? bio;'));
      // toJson must guard nullable field
      expect(src, contains('if (bio != null)'));
    });
  });

  group('ModelGenerator — copyWith sentinel', () {
    test(
      'copyWith uses _Undefined sentinel to allow clearing nullable fields',
      () {
        final doc = _makeDoc(
          schemas: {
            'Profile': const ObjectSchema(
              name: 'Profile',
              properties: [
                SchemaProperty(
                  specName: 'id',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: true,
                ),
                SchemaProperty(
                  specName: 'bio',
                  schema: PrimitiveSchema(primitiveType: 'string'),
                  isRequired: false,
                ),
              ],
              required: ['id'],
            ),
          },
        );
        final src = _source(doc, 'models/profile.dart');
        expect(src, contains('class _Undefined'));
        expect(src, contains('const _Undefined _undefined'));
        expect(src, contains('Object? bio = _undefined'));
        expect(src, contains('identical(bio, _undefined)'));
      },
    );
  });
}
