import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;
import 'package:pub_semver/pub_semver.dart';

/// Formats generated Dart sources and emits the barrel file for
/// [dart_openapi_generator].
///
/// Responsibilities:
/// - dart_style post-pass on every source string
/// - Emit a barrel file (named after `outputDir`'s last path segment) from
///   the complete file map
///
/// Actual disk I/O is the builder's job (`buildStep.writeAsString`), so
/// output stays tracked in build_runner's asset graph — this class only
/// prepares the final `{path: formattedSource}` map.
///
/// Usage:
/// ```dart
/// final formatted = FileWriter(onLog: (msg) => log.info(msg))
///     .prepare(allFiles, barrelFileName: 'generated.dart');
/// ```
final class FileWriter {
  final void Function(String)? onLog;
  final void Function(String)? onWarning;

  static final _formatter = DartFormatter(languageVersion: Version(3, 0, 0));

  const FileWriter({this.onLog, this.onWarning});

  /// Formats [files] and adds a barrel file (named [barrelFileName], e.g.
  /// `'generated.dart'`) exporting all of them. Returns the complete map,
  /// keyed by path relative to `outputDir`, in sorted-key order for
  /// determinism.
  Map<String, String> prepare(
    Map<String, String> files, {
    required String barrelFileName,
  }) {
    // Build barrel BEFORE adding it to allFiles to prevent self-export.
    // _emitBarrel receives only the original generator keys, which never
    // include the barrel's own key.
    final sortedKeys = (files.keys.toList()..sort());
    final barrelSource = _emitBarrel(sortedKeys, barrelFileName);

    final allFiles = {...files, barrelFileName: barrelSource};

    final result = <String, String>{};
    for (final key in (allFiles.keys.toList()..sort())) {
      // Security: reject file keys containing '..' or absolute paths before
      // they're used to construct an AssetId.
      if (key.contains('..') || p.isAbsolute(key)) {
        throw StateError(
          'dart_openapi_generator: unsafe file key "$key" — keys must be '
          'relative paths within outputDir and must not contain "..".',
        );
      }
      result[key] = _formatSafe(allFiles[key]!, key);
      onLog?.call('dart_openapi_generator: prepared $key');
    }
    return result;
  }

  /// Generates the barrel file exporting all [sortedKeys] in alphabetical
  /// order, excluding [barrelFileName] itself.
  String _emitBarrel(List<String> sortedKeys, String barrelFileName) {
    final exports = sortedKeys.where((k) => k != barrelFileName).toList();
    if (exports.isEmpty) {
      onWarning?.call('No files to export; $barrelFileName barrel is empty.');
    }
    return [
      '// GENERATED CODE - DO NOT MODIFY BY HAND',
      '// @dart=3.0',
      '// Generated by dart_openapi_generator',
      '',
      ...exports.map((path) => "export '$path';"),
      '',
    ].join('\n');
  }

  /// Formats [source] with [_formatter]. Returns [source] unmodified if the
  /// formatter throws (e.g., source contains a syntax error from a broken
  /// generator upstream — we still emit the file so the user can debug it).
  String _formatSafe(String source, String path) {
    try {
      return _formatter.format(source, uri: path);
    } on FormatterException catch (e) {
      onLog?.call('dart_openapi_generator: formatter error for $path — $e');
      return source;
    }
  }
}
