import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;
import 'package:pub_semver/pub_semver.dart';

import '../resolved_annotation.dart';

// Module-level singleton so concurrent _writeManifest calls share one CSPRNG
// and never produce the same suffix (avoids same-tick collision with Random()).
final _random = Random.secure();

/// Writes generated Dart files to disk for [dart_openapi_generator].
///
/// Responsibilities:
/// - Path safety guard (refuse dangerous outputDir values)
/// - cleanOutput: delete previous-run files before writing new ones
/// - dart_style post-pass on every source string
/// - Emit barrel file (generated.dart) from the complete file map
/// - dart:io File.writeAsString for each generated file
/// - Atomic manifest.json write to cachePath
///
/// Usage:
/// ```dart
/// await FileWriter(onLog: (msg) => log.info(msg)).write(allFiles, annotation);
/// ```
final class FileWriter {
  final void Function(String)? onLog;
  final void Function(String)? onWarning;

  static final _formatter = DartFormatter(languageVersion: Version(3, 0, 0));

  const FileWriter({this.onLog, this.onWarning});

  /// Formats and writes [files] to [annotation.outputDir], emits a barrel
  /// file (`generated.dart`), and persists the manifest.
  ///
  /// All writes are performed in sorted key order for determinism.
  /// If [ResolvedAnnotation.cleanOutput] is `true`, previous output files are
  /// deleted before any new files are written.
  Future<void> write(
    Map<String, String> files,
    ResolvedAnnotation annotation,
  ) async {
    // Resolve outputDir relative to project root (build_runner CWD = project root)
    final outputDir =
        p.isAbsolute(annotation.outputDir)
            ? annotation.outputDir
            : p.join(Directory.current.path, annotation.outputDir);

    _assertPathSafe(outputDir);

    if (annotation.cleanOutput) {
      await _clean(outputDir, annotation.cachePath);
    }

    // Build barrel BEFORE adding generated.dart to allFiles to prevent self-export.
    // _emitBarrel receives only the original generator keys, which never include
    // 'generated.dart' itself. After the barrel is built, allFiles is merged with
    // the barrel — preserving the self-exclusion invariant regardless of key ordering.
    final sortedKeys = (files.keys.toList()..sort());
    final barrelSource = _emitBarrel(sortedKeys);

    // Merged map: original files + barrel (generated.dart added AFTER barrel is built)
    final allFiles = {...files, 'generated.dart': barrelSource};

    final writtenPaths = <String>[];

    // Write files in sorted order for determinism
    for (final key in (allFiles.keys.toList()..sort())) {
      // Security: reject file keys containing '..' or absolute paths to prevent
      // path traversal attacks (mirrors the guard in _cleanFromManifest).
      if (key.contains('..') || p.isAbsolute(key)) {
        throw StateError(
          'dart_openapi_generator: unsafe file key "$key" — keys must be '
          'relative paths within outputDir and must not contain "..".',
        );
      }
      final rawSource = allFiles[key]!;
      final formatted = _formatSafe(rawSource, key);
      final absPath = p.join(outputDir, key);
      final file = File(absPath);
      await file.parent.create(recursive: true);
      await file.writeAsString(formatted);
      writtenPaths.add(key);
      onLog?.call('dart_openapi_generator: wrote $absPath');
    }

    await _writeManifest(annotation.cachePath, writtenPaths);
  }

  /// Generates the `generated.dart` barrel file exporting all [sortedKeys]
  /// in alphabetical order, excluding `generated.dart` itself.
  String _emitBarrel(List<String> sortedKeys) {
    final exports = sortedKeys.where((k) => k != 'generated.dart').toList();
    if (exports.isEmpty) {
      onWarning?.call('No files to export; generated.dart barrel is empty.');
    }
    return [
      '// GENERATED CODE - DO NOT MODIFY BY HAND',
      '// @dart=3.0',
      '// Generated by dart_openapi_generator',
      '',
      ...exports.map((path) => "export '$path';"),
      '',
    ].join('\n');
  }

  /// Formats [source] with [_formatter]. Returns [source] unmodified if the
  /// formatter throws (e.g., source contains a syntax error from a broken
  /// generator upstream — we still write the file so the user can debug it).
  String _formatSafe(String source, String path) {
    try {
      return _formatter.format(source, uri: path);
    } on FormatterException catch (e) {
      onLog?.call('dart_openapi_generator: formatter error for $path — $e');
      return source;
    }
  }

  /// Validates [outputDir] (already resolved to an absolute path, but before
  /// normalization) against a set of known-dangerous values. Throws [StateError]
  /// on any violation.
  ///
  /// Guards against: empty, filesystem root (`/`), project root (`.`), `lib`,
  /// path traversal (`..`), the project's `lib/` directory, and symlinks.
  void _assertPathSafe(String outputDir) {
    // Check for path traversal BEFORE normalization: p.normalize() removes '..'
    // segments, so 'lib/../secrets' would normalize to 'secrets' and evade the
    // post-normalization check. Check the raw resolved-but-not-normalized path first.
    // Compare path components rather than the raw string to avoid false positives
    // on directory names that contain ".." as a substring (e.g. "..config") but
    // are not actually traversal sequences.
    final rawParts = p.split(outputDir);
    if (rawParts.contains('..')) {
      throw StateError(
        'cleanOutput: outputDir "$outputDir" contains ".." path component which is disallowed.',
      );
    }

    final normalized = p.normalize(outputDir);

    // Empty or filesystem root
    if (normalized.isEmpty || normalized == '/') {
      throw StateError(
        'cleanOutput: outputDir "$outputDir" is unsafe (resolves to root or empty).',
      );
    }

    // Single-segment dangerous paths: '.', 'lib'
    final parts = p.split(normalized);
    if (parts.length == 1 && (parts[0] == '.' || parts[0] == 'lib')) {
      throw StateError('cleanOutput: outputDir "$outputDir" is unsafe.');
    }

    // Absolute path that resolves to the project root (e.g. outputDir == '.')
    final projectRoot = p.normalize(Directory.current.path);
    if (normalized == projectRoot) {
      throw StateError(
        'cleanOutput: outputDir "$outputDir" resolves to the project root directory, which is disallowed.',
      );
    }

    // Absolute path that is exactly the project lib directory
    final projectLib = p.join(Directory.current.path, 'lib');
    if (normalized == p.normalize(projectLib)) {
      throw StateError(
        'cleanOutput: outputDir "$outputDir" resolves to project lib directory, which is disallowed.',
      );
    }

    // Symlink
    if (FileSystemEntity.isLinkSync(normalized)) {
      throw StateError(
        'cleanOutput: outputDir "$normalized" is a symlink, which is disallowed.',
      );
    }
  }

  /// Deletes previous output files using the manifest when available, or
  /// falls back to the known-layout first-run strategy.
  Future<void> _clean(String outputDir, String cachePath) async {
    final manifestFile = File(p.join(cachePath, 'manifest.json'));
    if (await manifestFile.exists()) {
      await _cleanFromManifest(outputDir, manifestFile);
    } else {
      await _cleanFirstRun(outputDir);
    }
  }

  /// Deletes only the files listed in [manifestFile] within [outputDir].
  ///
  /// Each manifest entry is validated — entries containing `..` or absolute
  /// paths are skipped with a log message to defend against manifest poisoning.
  Future<void> _cleanFromManifest(String outputDir, File manifestFile) async {
    try {
      final content = await manifestFile.readAsString();
      final decoded = jsonDecode(content);
      if (decoded is! Map<String, dynamic>) {
        throw const FormatException('manifest root is not a JSON object');
      }
      final rawList = decoded['files'];
      if (rawList is! List) {
        throw const FormatException('manifest "files" is not a JSON array');
      }
      // Materialize a new List<String> (not a cast view) before sorting so that
      // ..sort() does not mutate the backing List<dynamic>.
      final fileList = rawList.whereType<String>().toList()..sort();
      for (final relPath in fileList) {
        // Security: validate each manifest entry is a relative path within
        // outputDir and does not contain '..'. Ignore entries that fail
        // validation (manifest poisoning protection).
        if (relPath.contains('..') || p.isAbsolute(relPath)) {
          onLog?.call(
            'dart_openapi_generator: skipping unsafe manifest entry "$relPath"',
          );
          continue;
        }
        final file = File(p.join(outputDir, relPath));
        if (file.existsSync()) {
          await file.delete();
          onLog?.call('dart_openapi_generator: deleted ${file.path}');
        }
      }
    } on FormatException catch (e) {
      onLog?.call(
        'dart_openapi_generator: manifest parse error — $e; falling back to first-run clean',
      );
      await _cleanFirstRun(outputDir);
    } on TypeError catch (e) {
      onLog?.call(
        'dart_openapi_generator: manifest type error — $e; falling back to first-run clean',
      );
      await _cleanFirstRun(outputDir);
    }
  }

  /// Deletes only the known output layout files when no manifest exists.
  ///
  /// Targets: `models/*.dart`, `services/*.dart`, `api_client.dart`,
  /// `generated.dart`. Does not perform recursive directory deletion.
  Future<void> _cleanFirstRun(String outputDir) async {
    for (final subdir in ['models', 'services']) {
      final dir = Directory(p.join(outputDir, subdir));
      if (await dir.exists()) {
        // Sort for deterministic deletion order
        final entities =
            await dir.list().toList()
              ..sort((a, b) => a.path.compareTo(b.path));
        for (final entity in entities) {
          if (entity is File && entity.path.endsWith('.dart')) {
            await entity.delete();
            onLog?.call('dart_openapi_generator: deleted ${entity.path}');
          }
        }
      }
    }
    for (final name in ['api_client.dart', 'generated.dart']) {
      final file = File(p.join(outputDir, name));
      if (await file.exists()) {
        await file.delete();
        onLog?.call('dart_openapi_generator: deleted ${file.path}');
      }
    }
  }

  /// Atomically writes the manifest file to `<cachePath>/manifest.json`.
  ///
  /// Writes to a uniquely-suffixed `.tmp` file first, then renames to the
  /// final path. Rename is atomic on the same filesystem, preventing torn
  /// reads from concurrent build invocations. Paths are sorted for
  /// deterministic manifest content.
  Future<void> _writeManifest(
    String cachePath,
    List<String> writtenPaths,
  ) async {
    final cacheDir = Directory(cachePath);
    await cacheDir.create(recursive: true);
    final finalFile = File(p.join(cachePath, 'manifest.json'));
    final suffix = _random.nextInt(0xFFFFFF).toRadixString(16).padLeft(6, '0');
    final tmpFile = File('${finalFile.path}.tmp.$suffix');
    // Sort paths for deterministic manifest content
    final sorted = writtenPaths.toList()..sort();
    var renamed = false;
    try {
      await tmpFile.writeAsString(jsonEncode({'files': sorted}));
      await tmpFile.rename(finalFile.path);
      renamed = true;
    } finally {
      if (!renamed && tmpFile.existsSync()) {
        await tmpFile.delete();
      }
    }
  }
}
