name: Run Tests

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get
        working-directory: ${{ inputs.working-directory }}

      - name: Test
        run: dart test
        working-directory: ${{ inputs.working-directory }}
